### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined while building using theme() fn

### ISSUE THREAD

**Issue by ahsath** [brandonpittman/gridsome-plugin-tailwindcss#12]
Hi, I've been using this plugin but while building my site I'm getting an error when using tailwindcss's `theme()` function inside Vue's SFC `<style>` tags

```
Gridsome v0.6.4

Initializing plugins...
Initialize - 1.9s
Load sources - 0s
Create GraphQL schema - 0.1s
Create pages and templates - 0.05s
Generate code - 0.03s
Bootstrap finish - 2.09s
Execute GraphQL (0 queries) - 0s
Write page data (0 files) - 0s
 10% building 1/1 m 92% chunk asset optimizationTypeError: Cannot read property 'length' of undefined                           at /Users/ahsath/Documents/repos/inkntint/assets/css/0.styles.d4d0eff9.css:1772:3                                
    at module.exports (/Users/ahsath/Documents/repos/inkntint/node_modules/postcss-value-parser/lib/unit.js:9:22)
    at args.forEach (/Users/ahsath/Documents/repos/inkntint/node_modules/postcss-minify-gradients/dist/index.js:66:61)
    at Array.forEach (<anonymous>)
    at decl.value.walk.node (/Users/ahsath/Documents/repos/inkntint/node_modules/postcss-minify-gradients/dist/index.js:60:18)
    at walk (/Users/ahsath/Documents/repos/inkntint/node_modules/postcss-value-parser/lib/walk.js:7:16)
    at ValueParser.walk (/Users/ahsath/Documents/repos/inkntint/node_modules/postcss-value-parser/lib/index.js:18:3)
    at optimise (/Users/ahsath/Documents/repos/inkntint/node_modules/postcss-minify-gradients/dist/index.js:43:59)
    at /Users/ahsath/Documents/repos/inkntint/node_modules/postcss/lib/container.js:190:18
    at /Users/ahsath/Documents/repos/inkntint/node_modules/postcss/lib/container.js:135:18
    at Rule.each (/Users/ahsath/Documents/repos/inkntint/node_modules/postcss/lib/container.js:101:16)
    at Rule.walk (/Users/ahsath/Documents/repos/inkntint/node_modules/postcss/lib/container.js:131:17)
    at /Users/ahsath/Documents/repos/inkntint/node_modules/postcss/lib/container.js:148:24
    at Root.each (/Users/ahsath/Documents/repos/inkntint/node_modules/postcss/lib/container.js:101:16)
    at Root.walk (/Users/ahsath/Documents/repos/inkntint/node_modules/postcss/lib/container.js:131:17)
    at Root.walkDecls (/Users/ahsath/Documents/repos/inkntint/node_modules/postcss/lib/container.js:188:19)
    at css (/Users/ahsath/Documents/repos/inkntint/node_modules/postcss-minify-gradients/dist/index.js:178:23)
```
```
<style>
.card-gradient--light {
  --to: "right";
  background-image: linear-gradient(
    to var(--to),
    white,
    theme("colors.blue.200")
  );
}
</style>
```
although it works fine on development, removing the function builds correctly.

**Comment by ahsath** [comment]
Actually the problem has nothing to do with the plugin, I was updating the `--to` css variable with a string and this it's not allowed
