### ISSUE TITLE
How to add a postcss plugin?

### ISSUE THREAD

**Issue by lynden-jones** [brandonpittman/gridsome-plugin-tailwindcss#21]
This is more of a question than an "issue".

Has anyone figured out how to add a postcss plugin that is not included?  If you can give me any hints it would be much appreciated!

I'm trying to add the rfs plugin (https://github.com/twbs/rfs) but everything I've tried doesn't seem to work.

In a vanilla vue cli project I'd just add this to the `postcss.config.js` file:

```
module.exports = {
  plugins: {
    tailwindcss: {},
    rfs: {},
    "vue-cli-plugin-tailwind/purgecss": {},
    autoprefixer: {}
  }
};
```

I've tried adding this to `gridsome.config.js`:

```
...
css: {
    loaderOptions: {
      postcss: {
        plugins: {
          'rfs': {}
        }
      }
    }
  }
```

But I get the following error:

```
$ gridsome develop
Gridsome v0.7.11

Initializing plugins...
Load sources - 7.7s
Create GraphQL schema - 0.1s
Create pages and templates - 0.07s
Generate temporary code - 0.05s
Bootstrap finish - 9.92s
TypeError: (postcss.plugins || []).concat is not a function
    at applyLoaders (~project/node_modules/gridsome/lib/webpack/createBaseConfig.js:298:44)
    at createCSSRule (~project/node_modules/gridsome/lib/webpack/createBaseConfig.js:271:5)
    at module.exports (~project/node_modules/gridsome/lib/webpack/createBaseConfig.js:150:3)
    at module.exports (~project/node_modules/gridsome/lib/webpack/createClientConfig.js:8:18)
    at Compiler.resolveChainableWebpackConfig (~project/node_modules/gridsome/lib/app/Compiler.js:23:25)
    at createWebpackConfig (~project/node_modules/gridsome/lib/develop.js:107:39)
    at module.exports (~project/node_modules/gridsome/lib/develop.js:28:31)
```

**Comment by brandonpittman** [comment]
@lynden-jones Shouldn't your `plugins` key be an array?

**Comment by lynden-jones** [comment]
Thank you @brandonpittman !  Not sure how I missed that.  The webpack feedback is not always helpful.
