### ISSUE TITLE
Cannot find module 'tailwindcss'

### ISSUE THREAD

**Issue by scottyzen** [brandonpittman/gridsome-plugin-tailwindcss#69]
Since the update I keep getting this error: Cannot find module 'tailwindcss'.

Here is the full log on a fresh project.
```json
Gridsome v0.7.22

Initializing plugins...
Error: Cannot find module 'tailwindcss'
Require stack:
- /Users/scott/Desktop/tailwindv2-master/node_modules/gridsome-plugin-tailwindcss/gridsome.server.js
- /Users/scott/Desktop/tailwindv2-master/node_modules/gridsome/lib/app/Plugins.js
- /Users/scott/Desktop/tailwindv2-master/node_modules/gridsome/lib/app/App.js
- /Users/scott/Desktop/tailwindv2-master/node_modules/gridsome/lib/app/index.js
- /Users/scott/Desktop/tailwindv2-master/node_modules/gridsome/lib/develop.js
- /Users/scott/Desktop/tailwindv2-master/node_modules/gridsome/index.js
- /usr/local/lib/node_modules/@gridsome/cli/bin/gridsome.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at new TailwindPlugin (/Users/scott/Desktop/tailwindv2-master/node_modules/gridsome-plugin-tailwindcss/gridsome.server.js:11:7)
    at Plugins.initialize (/Users/scott/Desktop/tailwindv2-master/node_modules/gridsome/lib/app/Plugins.js:61:11)
    at App.init (/Users/scott/Desktop/tailwindv2-master/node_modules/gridsome/lib/app/App.js:120:18)
    at App.bootstrap (/Users/scott/Desktop/tailwindv2-master/node_modules/gridsome/lib/app/App.js:49:16)
    at module.exports (/Users/scott/Desktop/tailwindv2-master/node_modules/gridsome/lib/app/index.js:12:18)
    at module.exports (/Users/scott/Desktop/tailwindv2-master/node_modules/gridsome/lib/develop.js:20:21)
    at /Users/scott/Desktop/tailwindv2-master/node_modules/gridsome/index.js:44:12
    at Command.<anonymous> (/Users/scott/Desktop/tailwindv2-master/node_modules/gridsome/index.js:13:44)
    at Command.listener (/usr/local/lib/node_modules/@gridsome/cli/node_modules/commander/index.js:315:8)
    at Command.emit (events.js:315:20)
    at Command.parseArgs (/usr/local/lib/node_modules/@gridsome/cli/node_modules/commander/index.js:651:12)
    at Command.parse (/usr/local/lib/node_modules/@gridsome/cli/node_modules/commander/index.js:474:21)
```

**Comment by brandonpittman** [comment]
Install Tailwind

**Comment by dsturm** [comment]
Hey @scottyzen,

as the [latest release](https://github.com/brandonpittman/gridsome-plugin-tailwindcss/releases/tag/4.1.0) changed to `peerDependencies` you need to install `tailwindcss` manually for your project.

**Comment by scottyzen** [comment]
Perfect. Thanks guys
